kind: pipeline
type: docker
name: ci

steps:
- name: test
  image: node
  environment:
    DOCKER_REGISTRY:
      from_secret: docker_registry
  commands:
  - echo $DOCKER_REGISTRY
  - yarn
  - yarn build